### PR TITLE
Update view saved covers

### PR DESCRIPTION
**Pull request by mbenfowler**
### Description

This pr will populate the `Saved Covers` view with all covers in our saved array.

### Testing Notes

- When a user clicks the “View Saved Covers” button, we should see the saved covers section
- All the covers in the savedCovers array should be displayed in the saved covers section

### CODE REVIEW

**Comment by CaliHam** [comment]
Screenshot 2023-03-31 at 2 07 14 PM
Right now, when you go to "View Saved Covers" and then go back home, and then go back into the "View Saved Covers", it multiplies the covers showing by two

**Comment by mbenfowler** [comment]
LOL @CaliHam I was wondering if you were gonna catch that one!!! 😆 
Definitely a bug - I'll see if I can't fix this one up here now.

**Review by CaliHam — APPROVED** [review]
It seems to be working great! This `appendCoversToSavedView()` is a pretty hefty function, maybe at the end we can look at refactoring using .innerHTML to simplify it for better readability. But otherwise looks and works great!

**Comment by mbenfowler** [comment]
@CaliHam I think you're absolutely right - there's gotta be a way to make this more DRY.  I'll look more into `innerHtml` as a potential solution and make a refactor ticket!

**Pull request merged**
